/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gestionetudiant;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author aba
 */
public class AjoutFilliereGui extends javax.swing.JPanel {
    Connection conn;
    int idSelectionner;

    /**
     * Creates new form AjoutFilliereGui
     */
    public AjoutFilliereGui() {
        conn = DbUtils.createConnection();
        initComponents();
    }
    
    public void initialiseFormulaire(int id, String nom){
        labelTitre.setText("Editer la filliére");
        nomFilliere.setText(nom);
        idSelectionner = id;
        errorLabel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomFilliere = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();
        boutonAjouter = new javax.swing.JButton();

        labelTitre.setBackground(new java.awt.Color(51, 51, 255));
        labelTitre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTitre.setText("Ajouter Une Filliére");
        labelTitre.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nom de la Filiére :");

        nomFilliere.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomFilliere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomFilliereActionPerformed(evt);
            }
        });

        errorLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 51));
        errorLabel.setToolTipText("");

        boutonAjouter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boutonAjouter.setText("Valider");
        boutonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(labelTitre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomFilliere, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(errorLabel)))
                .addContainerGap(263, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(boutonAjouter)
                .addGap(368, 368, 368))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelTitre)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomFilliere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(boutonAjouter)
                .addGap(28, 28, 28)
                .addComponent(errorLabel)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nomFilliereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomFilliereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomFilliereActionPerformed

    private void boutonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjouterActionPerformed
        String nom = nomFilliere.getText();
        if(nom.length() == 0){
            errorLabel.setText("Le nom de filliére doit etre rensegner");
        }else{
            nomFilliere.setText("");
            errorLabel.setForeground(new java.awt.Color(51, 51, 255));
            if (labelTitre.getText().equalsIgnoreCase("Ajouter Une Filliére")){
                try {
                    conn.createStatement().execute("insert into root.filliere (nom) VALUES ('"+nom+"')");
                    errorLabel.setText("Filliere ajouter avec succes");
                } catch (SQLException ex) {
                    Logger.getLogger(ListeEtudiantGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                 try {
                    conn.createStatement().executeUpdate(
                            "update root.filliere set nom = '"+nom+"' where id ="+idSelectionner+"");
                    errorLabel.setText("Filliere modifier avec succes");
                } catch (SQLException ex) {
                    Logger.getLogger(ListeEtudiantGui.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }
    }//GEN-LAST:event_boutonAjouterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAjouter;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelTitre;
    private javax.swing.JTextField nomFilliere;
    // End of variables declaration//GEN-END:variables
}
