/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gestionetudiant;

/**
 *
 * @author aba
 */
public class GestionEtudiantGui extends javax.swing.JFrame {

    /**
     * Creates new form GestionEtudiantGui
     */
    public GestionEtudiantGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AjouterEtudiantMenu = new javax.swing.JMenuItem();
        ListeEtudiantMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AjoutFilliereMenu = new javax.swing.JMenuItem();
        ListeFilliereMenu = new javax.swing.JMenuItem();
        QuitterMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Gestion de notre ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("école de Formation");

        jMenu1.setText("Etudiant");
        jMenu1.setToolTipText("");

        AjouterEtudiantMenu.setText("Ajouter");
        AjouterEtudiantMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterEtudiantMenuActionPerformed(evt);
            }
        });
        jMenu1.add(AjouterEtudiantMenu);

        ListeEtudiantMenu.setText("Liste");
        ListeEtudiantMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeEtudiantMenuActionPerformed(evt);
            }
        });
        jMenu1.add(ListeEtudiantMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Filliére");

        AjoutFilliereMenu.setText("Ajouter");
        AjoutFilliereMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutFilliereMenuActionPerformed(evt);
            }
        });
        jMenu2.add(AjoutFilliereMenu);

        ListeFilliereMenu.setText("Liste");
        ListeFilliereMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeFilliereMenuActionPerformed(evt);
            }
        });
        jMenu2.add(ListeFilliereMenu);

        jMenuBar1.add(jMenu2);

        QuitterMenu.setText("Quitter");
        jMenuBar1.add(QuitterMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addGap(248, 248, 248))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterEtudiantMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterEtudiantMenuActionPerformed
        AjoutEtudiantGui contenu = new AjoutEtudiantGui();
        setContentPane(contenu);
        repaint();
        validate();
    }//GEN-LAST:event_AjouterEtudiantMenuActionPerformed

    private void ListeEtudiantMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeEtudiantMenuActionPerformed
        ListeEtudiantGui contenu = new ListeEtudiantGui();
        setContentPane(contenu);
        repaint();
        validate();
    }//GEN-LAST:event_ListeEtudiantMenuActionPerformed

    private void AjoutFilliereMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutFilliereMenuActionPerformed
        AjoutFilliereGui contenu = new AjoutFilliereGui();
        setContentPane(contenu);
        repaint();
        validate();
    }//GEN-LAST:event_AjoutFilliereMenuActionPerformed

    private void ListeFilliereMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeFilliereMenuActionPerformed
        ListeFilliereGui contenu = new ListeFilliereGui();
        setContentPane(contenu);
        repaint();
        validate();
    }//GEN-LAST:event_ListeFilliereMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionEtudiantGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionEtudiantGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionEtudiantGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionEtudiantGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionEtudiantGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AjoutFilliereMenu;
    private javax.swing.JMenuItem AjouterEtudiantMenu;
    private javax.swing.JMenuItem ListeEtudiantMenu;
    private javax.swing.JMenuItem ListeFilliereMenu;
    private javax.swing.JMenu QuitterMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
